package com.flashguard.engine.emu

import com.flashguard.engine.core.FirmwareFacts
import com.flashguard.engine.fs.VirtualFs
import com.flashguard.engine.util.Hex
import com.flashguard.engine.util.Text
import java.io.BufferedReader
import java.io.InputStreamReader
import java.io.OutputStream
import java.net.InetAddress
import java.net.ServerSocket
import java.net.Socket
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicInteger

/**
 * Serves the firmware's own web files *byte-for-byte* on loopback so the user can preview them
 * in a WebView - without touching any real device.
 *
 * ANTI-FAKING RULES (these are the whole point of this class):
 *  - static files (HTML/CSS/JS/images) are served EXACTLY as stored in the image. No banner is
 *    injected into them, no "runtime data" is invented, no colours/fonts/menus are changed.
 *    What you see is what the firmware ships - including its broken bits.
 *  - native CGI binaries cannot execute on Android, so their URLs show an honest notice ("this
 *    page is generated by binary X on the real router and cannot run here") with a link to view
 *    the stored file's raw bytes. No fake form fields, no fake values, no fake menus.
 *  - there is NO login emulation. Many stock firmwares (e.g. TP-Link VxWorks) use HTTP Basic Auth
 *    (a browser popup), not an HTML form - inventing a login form would show a theme the real
 *    router never had. Static preview therefore browses read-only past any login, and says so.
 *  - there is NO invented "feature console" with made-up categories (VPN/IPv6/VoIP/...). The
 *    index is a plain listing of the REAL files and folders found in the image.
 *  - nothing is ever written back to the image or to any router.
 */
object WebUiLab {

    data class Route(
        val path: String,
        val kind: Kind,
        val feature: String,
        val title: String,
    ) {
        enum class Kind { STATIC, HANDLER, API, LOGIN }
    }

    data class Inventory(
        val routes: List<Route>,
        /** Real files grouped by their REAL parent folder - never by invented categories. */
        val features: Map<String, List<Route>>,
        val docRoot: String?,
        val loginPage: String?,
        val loginFormFields: List<String>,
        val loginAction: String?,
        val serverBinaries: List<String>,
        val title: String?,
        /** Always false now: FlashGuard never invents a login page. Kept for API compatibility. */
        val loginModelled: Boolean = false,
    ) {
        fun featureNames(): List<String> = features.keys.toList()
        val hasLoginForm: Boolean get() = loginPage != null
        val staticCount: Int get() = routes.count { it.kind == Route.Kind.STATIC || it.kind == Route.Kind.LOGIN }
        val handlerCount: Int get() = routes.count { it.kind == Route.Kind.HANDLER }
    }

    fun inventory(vfs: VirtualFs, facts: FirmwareFacts): Inventory {
        val roots = vfs.findWebRoots()
        val docRoot = roots.firstOrNull()
        val routes = ArrayList<Route>()

        for (e in vfs.allFiles()) {
            val p = e.path
            val low = p.lowercase()
            val ext = Text.ext(p)
            val inWebArea = roots.any { r -> p.startsWith(if (r.endsWith("/")) r else "$r/") }
            if (!inWebArea) continue
            val isHandler = low.contains("/cgi-bin/") || low.contains("/cgi/") ||
                ext in setOf("cgi", "lua", "asp", "php", "cgi-bin") ||
                (ext == "sh" && e.executable)
            val isPage = ext in setOf("html", "htm", "asp", "php", "lua", "js", "json")
            val baseName = Text.baseName(low)
            val isLogin = (baseName.startsWith("login") || low.contains("/login") || low.contains("auth") || low.contains("signin")) &&
                !baseName.startsWith("changelogin") && !baseName.contains("loginpwd") &&
                !isLoginErrorName(baseName)
            val kind = when {
                isLogin -> Route.Kind.LOGIN
                isHandler -> Route.Kind.HANDLER
                ext == "json" -> Route.Kind.API
                else -> Route.Kind.STATIC
            }
            if (!isPage && !isHandler) continue
            // Honest grouping: the file's real parent folder, not an invented "feature".
            val folder = Text.dirName(p)
            routes.add(Route(path = p, kind = kind, feature = folder, title = humanTitle(Text.baseName(p))))
        }

        if (routes.isEmpty() && docRoot != null) {
            routes.add(Route(docRoot, Route.Kind.STATIC, docRoot, "Document root"))
        }

        val features = LinkedHashMap<String, MutableList<Route>>()
        for (r in routes.sortedBy { it.path }) {
            features.getOrPut(r.feature) { ArrayList() }.add(r)
        }

        val loginCandidates = routes.filter { it.kind == Route.Kind.LOGIN }.map { it.path } +
            facts.loginPages
        val loginPage = pickLoginPage(vfs, loginCandidates, docRoot)
        // No static login form in the image (very common: stock firmwares often use HTTP Basic
        // Auth popups instead of HTML forms). The honest answer is "no login page to preview",
        // NOT an invented look-alike form.
        val loginHtml = loginPage?.let { vfs.readText(it, 65536) } ?: ""
        val loginFields = if (loginPage != null) parseLoginFields(loginHtml) else emptyList()
        val loginAction = loginPage?.let { parseFormAction(loginHtml) }

        val serverBins = listOf(
            "/usr/sbin/httpd", "/sbin/httpd", "/usr/bin/httpd", "/usr/sbin/uhttpd", "/sbin/uhttpd",
            "/usr/sbin/lighttpd", "/usr/sbin/nginx", "/usr/sbin/mini_httpd", "/usr/sbin/boa",
            "/usr/bin/mini_httpd", "/bin/boa", "/usr/sbin/goahead", "/bin/goahead", "/usr/bin/webs",
        ).filter { vfs.exists(it) }

        val title = docRoot?.let { root ->
            val index = listOf("index.html", "index.htm", "index.asp", "index.php", "index.lua", "home.html")
                .map { "$root/$it" }
                .firstOrNull { vfs.exists(it) }
            index?.let { vfs.readText(it, 8192)?.let { t -> Regex("<title>([^<]{1,80})</title>", RegexOption.IGNORE_CASE).find(t)?.groupValues?.get(1)?.trim() } }
        }

        return Inventory(
            routes, features, docRoot, loginPage, loginFields, loginAction, serverBins, title,
            loginModelled = false,
        )
    }

    /** Honest static-preview endpoints served under /__flashguard/. */
    const val INDEX_PATH = "/__flashguard/index"
    const val STATUS_PATH = "/__flashguard/status"
    const val RAW_PATH = "/__flashguard/raw"

    /**
     * Legacy path of the old invented login form. Kept so old bookmarks/tests get a redirect
     * to the honest entry point instead of a 404. Nothing is ever "modelled" behind it.
     */
    const val MODELLED_LOGIN_PATH = "/__flashguard/login"

    /** Name fragments that identify error/logout pages, which must never be picked as login pages. */
    private val LOGIN_ERROR_NAME_HINTS = listOf(
        "autherror", "auth_error", "errorpage", "error", "fail", "denied", "expired", "expire", "logout", "401",
    )

    private fun isLoginErrorName(baseName: String): Boolean {
        val n = baseName.lowercase()
        return LOGIN_ERROR_NAME_HINTS.any { n.contains(it) }
    }

    private fun pickLoginPage(vfs: VirtualFs, candidates: List<String>, docRoot: String?): String? {
        // Only a page that actually renders a login form qualifies: it must contain a password
        // input (or a form plus password wording). Pages that merely mention "password" - like the
        // classic TP-Link "AuthError.htm" troubleshooting page - are NOT login pages.
        val ordered = (
            candidates + listOfNotNull(
                docRoot?.let { "$it/login.html" }, docRoot?.let { "$it/login.htm" },
                docRoot?.let { "$it/index.html" },
            )
            ).distinct()
        for (c in ordered) {
            val text = vfs.readText(c, 65536) ?: continue
            if (isLoginErrorName(Text.baseName(c))) continue
            if (looksLikeLoginForm(text)) return c
        }
        return null
    }

    private fun looksLikeLoginForm(html: String): Boolean {
        val mentionsPassword = html.contains("password", true) ||
            html.contains("passwd", true) || html.contains("pwd", true)
        if (!mentionsPassword) return false
        val passwordInput = Regex("<input[^>]*type\\s*=\\s*[\"']?password", RegexOption.IGNORE_CASE)
            .containsMatchIn(html)
        val anyForm = html.contains("<form", true)
        return passwordInput || anyForm
    }

    private fun parseLoginFields(html: String): List<String> {
        val out = ArrayList<String>()
        val regex = Regex("<input[^>]*>", RegexOption.IGNORE_CASE)
        for (m in regex.findAll(html).take(20)) {
            val tag = m.value
            val type = Regex("type=[\"']?([a-zA-Z]+)", RegexOption.IGNORE_CASE).find(tag)?.groupValues?.get(1)
            val name = Regex("name=[\"']?([\\w\\[\\]-]+)", RegexOption.IGNORE_CASE).find(tag)?.groupValues?.get(1)
            if (name != null && (type == "text" || type == "password" || type == "hidden" || type == null)) {
                out.add("$name${if (type == "password") " (masked)" else ""}")
            }
        }
        return out
    }

    private fun parseFormAction(html: String): String? =
        Regex("<form[^>]*action=[\"']?([^\"' >]+)", RegexOption.IGNORE_CASE).find(html)?.groupValues?.get(1)

    private fun humanTitle(fileName: String): String {
        val base = fileName.substringBeforeLast('.')
        return base.replace('_', ' ').replace('-', ' ')
            .split(' ')
            .filter { it.isNotBlank() }
            .joinToString(" ") { w -> w.replaceFirstChar { if (it.isLowerCase()) it.titlecase() else it.toString() } }
    }

    /**
     * The loopback HTTP server for static preview.
     * Binds to 127.0.0.1 only: the phone's browser and the app can see it, nothing else.
     *
     * It is a READ-ONLY static file server over the extracted web root plus clearly-labelled
     * FlashGuard helper pages (file index, notices). It performs no authentication, invents no
     * data, and modifies no firmware bytes.
     */
    class Server(
        private val vfs: VirtualFs,
        private val inventory: Inventory,
        private val facts: FirmwareFacts,
        @Suppress("UNUSED_PARAMETER") defaultCreds: Pair<String, String> = "admin" to "admin",
    ) {
        private var serverSocket: ServerSocket? = null
        private var thread: Thread? = null
        private val running = AtomicBoolean(false)
        val requestCount = AtomicInteger(0)
        var port: Int = 0
            private set
        val requestLog = ArrayList<String>()

        /**
         * Always false: static preview performs no login. Kept for API compatibility so old
         * callers do not break; the honest state is "no session - read-only browsing".
         */
        var loggedIn: Boolean = false
            private set

        val baseUrl: String get() = "http://127.0.0.1:$port/"

        /**
         * Optional sink for app-level logging of server lifecycle.
         * Called from server threads; the sink must be thread-safe.
         */
        var eventSink: ((String) -> Unit)? = null

        private fun emit(message: String) {
            try {
                eventSink?.invoke(message)
            } catch (_: Throwable) {
            }
        }

        /** Thread-safe copy of the served-request log for the diagnostics report. */
        @Synchronized
        fun requestLogSnapshot(): List<String> = ArrayList(requestLog)

        /**
         * The URL path a browser opens first: the image's own login page when it ships a real
         * HTML login form, otherwise the honest file index. Never an invented page.
         */
        val loginUrl: String
            get() = inventory.loginPage?.let { page ->
                val docRoot = inventory.docRoot
                if (docRoot != null && page.startsWith(if (docRoot.endsWith("/")) docRoot else "$docRoot/")) {
                    "/" + page.removePrefix(if (docRoot.endsWith("/")) docRoot else "$docRoot/")
                } else {
                    "/" + page.removePrefix("/")
                }
            } ?: INDEX_PATH

        fun start(): Boolean = try {
            val ss = ServerSocket(0, 16, InetAddress.getByName("127.0.0.1"))
            serverSocket = ss
            port = ss.localPort
            running.set(true)
            thread = Thread({ acceptLoop(ss) }, "flashguard-webui-emu").apply {
                isDaemon = true
                start()
            }
            emit("web server started on 127.0.0.1:$port (static preview, read-only, no login)")
            true
        } catch (t: Throwable) {
            emit("web server failed to start: ${t.message ?: t.javaClass.simpleName}")
            false
        }

        fun stop() {
            running.set(false)
            try {
                serverSocket?.close()
            } catch (_: Throwable) {
            }
            thread?.interrupt()
            emit("web server stopped after $requestCount request(s)")
        }

        private fun acceptLoop(ss: ServerSocket) {
            while (running.get()) {
                try {
                    val socket = ss.accept()
                    handle(socket)
                } catch (t: Throwable) {
                    if (!running.get()) return
                }
            }
        }

        private fun handle(socket: Socket) {
            try {
                socket.soTimeout = 4000
                val reader = BufferedReader(InputStreamReader(socket.getInputStream(), Charsets.ISO_8859_1))
                val requestLine = reader.readLine() ?: return
                val parts = requestLine.split(' ')
                if (parts.size < 2) return
                val method = parts[0]
                val rawPath = parts[1]
                val query = rawPath.substringAfter('?', "").take(2048)
                val path = Text.normPath(rawPath.substringBefore('?').ifBlank { "/" })
                var contentLength = 0
                while (true) {
                    val line = reader.readLine() ?: break
                    if (line.isEmpty()) break
                    when {
                        line.startsWith("Content-Length:", true) -> contentLength = line.substringAfter(':').trim().toIntOrNull() ?: 0
                    }
                }
                if (contentLength in 1..65536) {
                    // Drain the body so the connection stays clean; form submissions are answered
                    // with an honest notice below (the handler binary cannot run here).
                    val buf = CharArray(contentLength)
                    var read = 0
                    while (read < contentLength) {
                        val n = reader.read(buf, read, contentLength - read)
                        if (n < 0) break
                        read += n
                    }
                }
                requestCount.incrementAndGet()

                val out = socket.getOutputStream()
                when {
                    path.startsWith("/__flashguard/") -> {
                        logRequest("$method $path${if (query.isNotEmpty()) "?$query" else ""}")
                        handleInternal(path, query, out)
                    }
                    method == "POST" -> {
                        // No form on any firmware can actually be submitted in static preview:
                        // the receiving binary cannot execute on Android. Say so plainly.
                        logRequest("$method $path (form submission not executed)")
                        serveNotice(
                            out,
                            "Forms cannot be submitted in static preview",
                            "The form on <code>${escape(path)}</code> would be handled on the real router " +
                                "by a native program that cannot run on this phone, so nothing was submitted " +
                                "and nothing changed. This preview is read-only.<br><br>" +
                                "<a href=\"$INDEX_PATH\">Open the file index</a> to browse the pages this image actually ships.",
                            501,
                        )
                    }
                    else -> {
                        val alias = aliasFor(path)
                        val serving = alias ?: path
                        if (alias != null && alias != path) {
                            logRequest("GET $path -> $alias (same file, stored flat in image)")
                        } else {
                            logRequest("GET $path")
                        }

                        if (path == "/") {
                            val index = indexFile()
                            if (index != null) serveStatic(index, out)
                            else redirect(out, INDEX_PATH)
                        } else {
                            val entry = if (alias != null) vfs.get(alias) else vfs.get(path)
                            if (entry != null && !entry.isDir && looksStatic(serving)) {
                                // Raw bytes, exactly as stored. No banner, no injected data.
                                serveStatic(serving, out)
                            } else {
                                val route = inventory.routes.firstOrNull { it.path.equals(serving, true) || it.path.equals(path, true) }
                                if (entry != null && !entry.isDir && route != null && route.kind == Route.Kind.HANDLER) {
                                    serveHandlerNotice(route.path, out)
                                } else if (entry == null && route != null && route.kind == Route.Kind.HANDLER) {
                                    serveHandlerNotice(route.path, out)
                                } else if (entry == null) {
                                    serveNotFound(path, out)
                                } else if (entry.isDir) {
                                    serveDirectory(path, out)
                                } else {
                                    // A stored file with a non-static extension (template/source):
                                    // offer its raw bytes rather than pretending to render it.
                                    serveHandlerNotice(serving, out)
                                }
                            }
                        }
                    }
                }
                out.flush()
                socket.close()
            } catch (t: Throwable) {
                try {
                    socket.close()
                } catch (_: Throwable) {
                }
            }
        }

        @Synchronized
        private fun logRequest(line: String) {
            if (requestLog.size < 300) requestLog.add(line)
        }

        private fun indexFile(): String? {
            val docRoot = inventory.docRoot ?: return null
            val names = listOf("index.html", "index.htm", "index.asp", "index.php", "index.lua", "home.html")
            for (name in names) {
                val exact = Text.normPath("$docRoot/$name")
                if (vfs.isFile(exact)) return exact
                vfs.list(docRoot).firstOrNull { it.name.equals(name, ignoreCase = true) }?.let { return it.path }
            }
            return null
        }

        /**
         * Maps "/x" to "<docroot>/x" when the image stores its UI under a web root. Images that
         * flatten their web store into one directory (TP-Link VxWorks does this) still reference
         * "/userRpm/MenuRpm.htm" or "/images/top.jpg" from their pages, so as a last resort the
         * file is looked up by its base name UNDER THE DOC ROOT ONLY. This serves the image's own
         * real bytes under the path its own pages ask for - it never substitutes another file's
         * content and never invents a response.
         */
        private fun aliasFor(path: String): String? {
            val docRoot = inventory.docRoot ?: return null
            if (path.startsWith(docRoot)) return path
            val candidate = Text.normPath("$docRoot/$path")
            if (vfs.exists(candidate)) return candidate
            // Case-insensitive match inside the doc root (Index.htm vs index.htm).
            val lower = candidate.lowercase()
            vfs.allFiles().firstOrNull {
                it.path.lowercase() == lower &&
                    it.path.startsWith(if (docRoot.endsWith("/")) docRoot else "$docRoot/")
            }?.let { return it.path }
            // Flattened-store fallback: unique base-name match under the doc root only.
            val base = Text.baseName(path)
            if (base.isEmpty() || base == "/") return null
            val underDocRoot = vfs.findByName(base).filter { it.path.startsWith(if (docRoot.endsWith("/")) docRoot else "$docRoot/") }
            if (underDocRoot.size == 1) return underDocRoot[0].path
            // Ambiguous (same name in several folders): never guess - let the 404 page explain.
            return null
        }

        private fun looksStatic(path: String): Boolean {
            val ext = Text.ext(path)
            return ext in setOf("html", "htm", "js", "css", "png", "gif", "jpg", "jpeg", "svg", "ico", "txt", "json", "woff", "woff2", "xml")
        }

        private fun handleInternal(path: String, query: String, out: OutputStream) {
            when {
                path == STATUS_PATH -> {
                    val json = buildString {
                        append("{")
                        append("\"emulated\":true,")
                        append("\"mode\":\"static-preview-read-only\",")
                        append("\"requests\":${requestCount.get()},")
                        append("\"loggedIn\":false,")
                        append("\"docRoot\":\"${escapeJson(inventory.docRoot ?: "")}\",")
                        append("\"loginPage\":\"${escapeJson(inventory.loginPage ?: "")}\",")
                        append("\"hasLoginForm\":${inventory.hasLoginForm},")
                        append("\"loginModelled\":false,")
                        append("\"loginUrl\":\"${escapeJson(loginUrl)}\",")
                        append("\"staticFiles\":${inventory.staticCount},")
                        append("\"handlers\":${inventory.handlerCount},")
                        append("\"folders\":[").append(inventory.featureNames().joinToString(",") { "\"${escapeJson(it)}\"" }).append("],")
                        append("\"serverBinaries\":[").append(inventory.serverBinaries.joinToString(",") { "\"${escapeJson(it)}\"" }).append("],")
                        append("\"note\":\"Raw firmware bytes only. No authentication, no CGI execution, no invented data.\"")
                        append("}")
                    }
                    respond(out, 200, "application/json", json.toByteArray(Charsets.UTF_8))
                }
                path == INDEX_PATH -> {
                    respond(out, 200, "text/html", indexHtml().toByteArray(Charsets.UTF_8))
                }
                path == RAW_PATH -> {
                    serveRaw(query, out)
                }
                // Backwards compatibility: the old invented console/login/logout endpoints now
                // redirect to the honest entry points instead of serving invented pages.
                path == "/__flashguard/console" -> redirect(out, INDEX_PATH)
                path == MODELLED_LOGIN_PATH -> redirect(out, loginUrl)
                path == "/__flashguard/logout" -> redirect(out, INDEX_PATH)
                else -> respond(out, 404, "text/plain", "unknown internal endpoint".toByteArray())
            }
        }

        /**
         * Plain listing of the REAL files and folders found in the image. Explicitly labelled as
         * a FlashGuard helper page - never styled to look like router UI.
         */
        private fun indexHtml(): String {
            val sb = StringBuilder()
            sb.append("<!DOCTYPE html><html><head><meta charset=\"utf-8\">")
            sb.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">")
            sb.append("<title>Static file index - FlashGuard preview</title>")
            sb.append("<style>body{font-family:system-ui,sans-serif;margin:0;background:#F4F6F8;color:#17202A;padding:0 0 40px}")
            sb.append("header{padding:16px;background:#1F3A4D;color:#fff}")
            sb.append("h1{font-size:17px;margin:0 0 6px}h2{font-size:14px;margin:20px 0 6px;color:#1F3A4D}")
            sb.append("main{padding:0 16px;max-width:900px}p,li{font-size:13px;line-height:1.55}")
            sb.append(".warn{background:#FFF3CD;border:1px solid #D9B800;border-radius:6px;padding:10px 12px;font-size:12.5px}")
            sb.append("code{background:#E7EDF2;padding:1px 5px;border-radius:4px;font-size:12px}")
            sb.append("a{color:#0B5CAD}table{border-collapse:collapse;width:100%;font-size:12.5px}")
            sb.append("td,th{border-bottom:1px solid #D5DCE3;padding:5px 8px;text-align:left;vertical-align:top}")
            sb.append("th{background:#E7EDF2}.tag{font-size:11px;background:#D5DCE3;border-radius:10px;padding:1px 8px;white-space:nowrap}")
            sb.append("</style></head><body>")
            sb.append("<header><h1>Static file index - this page is FlashGuard, not the router</h1>")
            sb.append("<div style=\"font-size:12.5px\">Every link below opens a file <b>exactly as stored</b> in the firmware image. ")
            sb.append("No login was performed, nothing was executed, nothing was changed.</div></header><main>")

            val docRoot = inventory.docRoot
            if (docRoot == null) {
                sb.append("<p class=\"warn\">No web root was found in this image, so there is no web UI to preview.</p>")
            } else {
                val webFiles = vfs.allFiles()
                    .filter { it.path.startsWith(if (docRoot.endsWith("/")) docRoot else "$docRoot/") }
                    .sortedBy { it.path }
                sb.append("<p class=\"warn\"><b>Read-only static preview.</b> Pages that need live router data ")
                sb.append("(status values, menus built by the router's own program) show their stored template ")
                sb.append("as-is - blank or broken where the live data would go. That is honest: FlashGuard does not invent the missing values.</p>")
                sb.append("<p>Document root: <code>${escape(docRoot)}</code> &middot; ")
                sb.append("${webFiles.size} file(s) &middot; ")
                if (inventory.loginPage != null) {
                    sb.append("login form found: <code>${escape(inventory.loginPage!!)}</code>")
                } else {
                    sb.append("no HTML login form in this image (many stock firmwares use a browser password popup instead)")
                }
                sb.append("</p>")
                // Entry points the image itself provides.
                val index = indexFile()
                if (index != null) {
                    val url = "/" + index.removePrefix(if (docRoot.endsWith("/")) docRoot else "$docRoot/")
                    sb.append("<p>Start page shipped by the image: <a href=\"${escape(url)}\"><code>${escape(index)}</code></a></p>")
                }
                if (webFiles.isEmpty()) {
                    sb.append("<p>No files were extracted under the document root.</p>")
                } else {
                    val byDir = webFiles.groupBy { Text.dirName(it.path) }.toSortedMap()
                    for ((dir, files) in byDir) {
                        sb.append("<h2><code>${escape(dir)}</code> <span class=\"tag\">${files.size} file(s)</span></h2>")
                        sb.append("<table><tr><th>File (real name in image)</th><th>Size</th><th>Preview</th></tr>")
                        for (f in files.take(400)) {
                            val rel = f.path.removePrefix(if (docRoot.endsWith("/")) docRoot else "$docRoot/")
                            val url = "/$rel"
                            val kind = if (looksStatic(f.path)) "static" else "needs router program"
                            sb.append("<tr><td><code>${escape(f.name)}</code><br><span style=\"color:#5D6D7E\">${escape(f.path)}</span></td>")
                            sb.append("<td style=\"white-space:nowrap\">${escape(Hex.humanBytes(f.size))}</td>")
                            sb.append("<td><a href=\"${escape(url)}\">$kind</a></td></tr>")
                        }
                        if (files.size > 400) sb.append("<tr><td colspan=\"3\">... ${files.size - 400} more file(s) not listed</td></tr>")
                        sb.append("</table>")
                    }
                }
            }
            if (inventory.serverBinaries.isNotEmpty()) {
                sb.append("<h2>Web server programs found in this image (not executed)</h2><ul>")
                for (b in inventory.serverBinaries) sb.append("<li><code>${escape(b)}</code></li>")
                sb.append("</ul>")
            }
            sb.append("<h2>Firmware identity (from analysis, not from the web UI)</h2><ul>")
            sb.append("<li>Distribution: <b>${escape(facts.distro ?: "unknown")} ${escape(facts.firmwareVersion ?: "")}</b></li>")
            sb.append("<li>Target: <code>${escape(facts.target ?: "unknown")}</code> Arch: <code>${escape(facts.arch ?: "unknown")}</code></li>")
            sb.append("</ul>")
            sb.append("<p><a href=\"$STATUS_PATH\">status.json</a></p>")
            sb.append("</main></body></html>")
            return sb.toString()
        }

        /**
         * Honest notice for URLs whose content is generated on the real router by a native
         * program. Shows what IS known (the stored file, its size) and offers the raw bytes.
         */
        private fun serveHandlerNotice(storedPath: String, out: OutputStream) {
            val entry = vfs.get(storedPath)
            val size = entry?.let { Hex.humanBytes(it.size) } ?: "unknown size"
            val rawLink = "$RAW_PATH?path=${urlEncode(storedPath)}"
            serveNotice(
                out,
                "This page needs the router itself - not previewed",
                "On the real router, <code>${escape(storedPath)}</code> ($size) is produced by a native " +
                    "program that cannot run on this phone, so FlashGuard shows this notice instead of " +
                    "inventing what the page would contain.<br><br>" +
                    "What you can do: <a href=\"$rawLink\">view the stored file's raw bytes</a> (template/source as shipped), " +
                    "or <a href=\"$INDEX_PATH\">browse the file index</a> for pages that preview as-is.",
                200,
            )
        }

        private fun serveNotFound(path: String, out: OutputStream) {
            val docRoot = inventory.docRoot
            val hint = if (docRoot != null) {
                val base = Text.baseName(path)
                val sameName = if (base.isNotEmpty()) vfs.findByName(base).filter {
                    it.path.startsWith(if (docRoot.endsWith("/")) docRoot else "$docRoot/")
                } else emptyList()
                when {
                    sameName.size > 1 -> "<br><br>Note: <code>${escape(base)}</code> exists in ${sameName.size} folders under " +
                        "<code>${escape(docRoot)}</code>, so FlashGuard did not guess which one this URL means. " +
                        "Use the file index to open the exact file."
                    else -> ""
                }
            } else ""
            serveNotice(
                out,
                "404 - not in this image",
                "Path <code>${escape(path)}</code> does not exist in the extracted web files$hint<br><br>" +
                    "<a href=\"$INDEX_PATH\">Open the file index</a> to see what the image actually ships.",
                404,
            )
        }

        private fun serveDirectory(path: String, out: OutputStream) {
            val kids = vfs.childNames(path).sorted().take(100)
            val items = if (kids.isEmpty()) "empty directory" else kids.joinToString(", ") { escape(it) }
            serveNotice(
                out,
                "Directory listing: ${escape(path)}",
                "Files: $items<br><br><a href=\"$INDEX_PATH\">Open the full file index</a>.",
                200,
            )
        }

        /** Serves raw bytes of a stored web file for inspection (never executed). */
        private fun serveRaw(query: String, out: OutputStream) {
            val params = parseQuery(query)
            val rawPath = params["path"] ?: run {
                respond(out, 400, "text/plain", "missing path parameter".toByteArray())
                return
            }
            val norm = Text.normPath(rawPath)
            val docRoot = inventory.docRoot
            val allowed = when {
                docRoot != null && (norm == docRoot || norm.startsWith(if (docRoot.endsWith("/")) docRoot else "$docRoot/")) -> true
                inventory.routes.any { it.path.equals(norm, true) } -> true
                else -> false
            }
            if (!allowed) {
                respond(out, 403, "text/plain", "path is outside the extracted web root".toByteArray())
                return
            }
            val bytes = vfs.read(norm)
            if (bytes == null) {
                respond(out, 404, "text/plain", "file bytes are not available (not kept in RAM)".toByteArray())
                return
            }
            respond(out, 200, "text/plain; charset=utf-8", bytes)
        }

        /** Serves one static file EXACTLY as stored - the bytes are never modified. */
        private fun serveStatic(path: String, out: OutputStream) {
            val bytes = vfs.read(path) ?: run {
                respond(out, 404, "text/plain", "not found".toByteArray())
                return
            }
            val mime = mimeOf(path)
            // No charset override on HTML: the file's own <meta> tag decides, exactly as the
            // vendor shipped it. Anything else would change how the page renders.
            respond(out, 200, mime, bytes)
        }

        private fun parseQuery(raw: String): Map<String, String> {
            if (raw.isBlank()) return emptyMap()
            val out = LinkedHashMap<String, String>()
            for (part in raw.split('&').take(16)) {
                if (part.isEmpty()) continue
                out[urlDecode(part.substringBefore('=', ""))] = urlDecode(part.substringAfter('=', ""))
            }
            return out
        }

        private fun urlEncode(s: String): String {
            val sb = StringBuilder()
            for (b in s.toByteArray(Charsets.UTF_8)) {
                val c = b.toInt() and 0xFF
                if (c in 0x30..0x39 || c in 0x41..0x5A || c in 0x61..0x7A || c == '/'.code || c == '.'.code || c == '_'.code || c == '-'.code) {
                    sb.append(c.toChar())
                } else {
                    sb.append('%').append(String.format("%02X", c))
                }
            }
            return sb.toString()
        }

        private fun urlDecode(s: String): String {
            val bytes = ArrayList<Byte>(s.length)
            var i = 0
            while (i < s.length) {
                when (val c = s[i]) {
                    '+' -> { bytes.add(' '.code.toByte()); i++ }
                    '%' -> {
                        if (i + 2 < s.length) {
                            val hex = s.substring(i + 1, i + 3)
                            val v = hex.toIntOrNull(16)
                            if (v != null && v in 0..255) {
                                bytes.add(v.toByte()); i += 3
                            } else {
                                bytes.add(c.code.toByte()); i++
                            }
                        } else {
                            bytes.add(c.code.toByte()); i++
                        }
                    }
                    else -> { bytes.add(c.code.toByte()); i++ }
                }
            }
            return String(bytes.toByteArray(), Charsets.UTF_8)
        }

        /**
         * Clearly-labelled FlashGuard helper page. Deliberately plain and visually distinct from
         * any router UI so it can never be mistaken for firmware content.
         */
        private fun serveNotice(out: OutputStream, title: String, bodyHtml: String, status: Int) {
            val html =
                "<!DOCTYPE html><html><head><meta charset=\"utf-8\">" +
                    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">" +
                    "<title>${escape(title)} - FlashGuard preview</title>" +
                    "<style>body{font-family:system-ui,sans-serif;background:#F4F6F8;color:#17202A;padding:18px;max-width:800px}" +
                    "h1{font-size:16px;color:#1F3A4D}.tag{display:inline-block;background:#1F3A4D;color:#fff;" +
                    "border-radius:4px;padding:2px 8px;font-size:11px;margin-bottom:10px}" +
                    "code{background:#E7EDF2;padding:1px 5px;border-radius:4px;font-size:12px}" +
                    "a{color:#0B5CAD}p{font-size:13.5px;line-height:1.6}</style></head><body>" +
                    "<div class=\"tag\">FLASHGUARD PREVIEW NOTICE - NOT THE ROUTER UI</div>" +
                    "<h1>${escape(title)}</h1><p>$bodyHtml</p>" +
                    "<p><a href=\"$INDEX_PATH\">File index</a> &middot; " +
                    "<a href=\"$STATUS_PATH\">status.json</a></p></body></html>"
            respond(out, status, "text/html", html.toByteArray(Charsets.UTF_8))
        }

        private fun redirect(out: OutputStream, location: String) {
            val body = "<html><body>Redirecting to <a href=\"${escape(location)}\">${escape(location)}</a></body></html>"
            val head = "HTTP/1.1 302 Found\r\nLocation: $location\r\nContent-Type: text/html\r\nContent-Length: ${body.length}\r\nConnection: close\r\n\r\n"
            out.write((head + body).toByteArray(Charsets.ISO_8859_1))
        }

        private fun respond(out: OutputStream, status: Int, contentType: String, body: ByteArray) {
            val head = "HTTP/1.1 $status ${statusText(status)}\r\n" +
                "Content-Type: $contentType\r\n" +
                "Content-Length: ${body.size}\r\n" +
                "X-FlashGuard: static-preview-read-only\r\n" +
                "Cache-Control: no-store\r\n" +
                "Connection: close\r\n\r\n"
            out.write(head.toByteArray(Charsets.ISO_8859_1))
            out.write(body)
        }

        private fun statusText(code: Int): String = when (code) {
            200 -> "OK"; 302 -> "Found"; 400 -> "Bad Request"; 403 -> "Forbidden"
            404 -> "Not Found"; 500 -> "Internal Server Error"; 501 -> "Not Implemented"; else -> "OK"
        }

        private fun mimeOf(path: String): String = when (Text.ext(path)) {
            "html", "htm" -> "text/html"
            "css" -> "text/css"
            "js" -> "application/javascript"
            "json" -> "application/json"
            "png" -> "image/png"
            "gif" -> "image/gif"
            "jpg", "jpeg" -> "image/jpeg"
            "svg" -> "image/svg+xml"
            "ico" -> "image/x-icon"
            "xml" -> "application/xml"
            "txt" -> "text/plain"
            else -> "application/octet-stream"
        }
    }

    private fun escape(s: String): String = s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;")

    private fun escapeJson(s: String): String = s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", " ")
}
